name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      NODE_ENV: production
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencys
      run: |
          npm install --include=dev
    - name: Wait for PostgreSQL to be ready
      run: |
          until pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 20
          done
    - name: Run Gulp build
      env:
          DB_USER: postgres
          DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DB_HOST: postgres
      run: |
        gulp 

    - name: List node_modules
      run: |
        dir node_modules

    - name: Build Docker images
      run: |
        docker build -t  gulp-frontend-1 romanarmin/gulpApp-frontend:v1
        docker build -t gulp-backend-1 romanarmin/gulpApp-backend:v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images
      run: |
        docker push romanarmin/gulpApp-frontend:v1
        docker push romanarmin/gulpApp-backend:v1

    - name: Test the App
      run: |
        npm run test
